### ISSUE TITLE
Chapter intro needs to fit on a single page

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#83] opened 2024-07-04 09:27 UTC
Chapter intros contains keywords and learning objectives and should fit the content on one page.
Unfortunately, for CTFL chapter 5, the content overflows the page by one line in all languages.

![image](https://github.com/istqborg/istqb_product_base/assets/95688217/5c415f03-35c8-4ac9-b238-4013b72494e9)

Solutions could be:

1. Make footer smaller by merging two sections into one as ISTQB template now prescribes
![image](https://github.com/istqborg/istqb_product_base/assets/95688217/55bf783d-059d-43cf-9690-be1c861d3ea0)
2. Lower margins around Keywors and Learning Objectives headers
3. LaTeX magic :)

**Comment by Witiko** [comment] 2024-07-22 18:10
@danopolan After closing ticket https://github.com/istqborg/istqb_product_base/issues/86, there is slightly less space after chapter headings that are not immediately followed by section headings. This fixes the issue in the Chapter 5 of the English CTFL syllabus:

![image](https://github.com/user-attachments/assets/5a9188da-1b8f-402b-ba25-6c964b4b7dd8)

**Comment by Witiko** [comment] 2024-07-31 10:18
Closing PR https://github.com/istqborg/istqb_product_base/pull/88 reopens this issue.

**Comment by Witiko** [comment] 2024-08-01 10:55
I could not reproduce the issue with commit 57383447b89a57bf13069a31b13526e26727fb19 from current branch `main`, see the left image below. Regardless, in commit b41f96c from PR https://github.com/istqborg/istqb_product_base/pull/89, I shrinked the vertical space above **Keywords** and **Learning Objectives** to reduce the chance of a chapter intro not fitting on a single page:

![image](https://github.com/user-attachments/assets/c53156e4-4c3f-41f7-b587-e71235e3e1af)

**Closed** 2024-08-08 16:26 UTC
