### ISSUE TITLE
Some Table of Content links leads to page break on previous page

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#128] opened 2024-11-02 14:25 UTC
Some links in the Table of Content leads to the end of the content on previous page, rather than heading on a respective page.

Examples are across all documents, but I have found these:

- Contents (from document bookmarks) - All documents
- Chapter level 1 headings (except Copyright, Revision History, Acknowledgments) and appendices (except References, Apx B Traceability Matrix and Apx C Release Notes) - Syllabus

<img width="1497" alt="image" src="https://github.com/user-attachments/assets/6288fbd6-d02e-48c7-9a5d-fd2e198b17dc">

**Comment by Witiko** [comment] 2024-12-04 17:37
> * Contents (from document bookmarks) - All documents

I can reproduce this and I fixed it in https://github.com/istqborg/istqb_product_base/pull/154.

> * Chapter level 1 headings (except Copyright, Revision History, Acknowledgments) and appendices (except References, Apx B Traceability Matrix and Apx C Release Notes) - Syllabus

I can't reproduce with the current version of the document from the screenshot (`syllabus-en.tex` from [istqborg/istqb-ctal-ta](https://github.com/istqborg/istqb-ctal-ta)):

![image](https://github.com/user-attachments/assets/7a25d1a3-bb4b-4d56-9738-d73dc1344c7b)

Can you, @danopolan?

**Comment by danopolan** [comment] 2024-12-04 21:50
> Can you, @danopolan?

I have tried TA and TAS syllabi form the latest runs and I cannot. So we will ignore it for now, despite I am not sure why it did start working.

**Comment by Witiko** [comment] 2024-12-04 23:00
> I am not sure why it did start working.

This may have been fixed in commit https://github.com/istqborg/istqb_product_base/pull/136/commits/795c303e07b4e7119ecd7e8bd768fb5a55399d09 from https://github.com/istqborg/istqb_product_base/pull/136.

**Closed** 2024-12-04 23:00 UTC
