### ISSUE TITLE
TAE pipeline failure

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#137] opened 2024-11-08 12:26 UTC
LaTeX is failing to build syllabus-de.tex due to error we cannot fix by updating the content. Can you please have a look?

https://github.com/istqborg/istqb-ct-tas/commit/67f20dcd66cb7966a49ae26cff7e83f1ed12a616

Cc: @JaGi-GTB

**Comment by danopolan** [comment] 2024-11-08 14:52
Message from Jan:
I have merged the branches "Syllabus" and "Exam". Now it is building again. 

In the "Sample Exam" branch, newer changes of the syllabus-de.tex were not included. Probably the problem.

**Comment by Witiko** [comment] 2024-11-08 19:47
I am glad that the issue is solved but I don't think we have discovered or removed the root cause.

As discussed, the issue is due to the document not converging to a stable output after 10 compilation passes. To see what the difference was, I compiled the document 10 and 11 times. Below is the only part of the document that is different:

![Screenshot from 2024-11-08 20-41-55](https://github.com/user-attachments/assets/803fa9b0-e2b3-46aa-b7fb-472535f65fcf)

Apparently, the websites oscillate between being / not being displayed for no apparent reason. I will look into this further.

**Comment by Witiko** [comment] 2024-11-08 20:40
Here is the reason for why this is happening: The file `syllabus-de.tex` contains the command `\nocite{*}` to include uncited references in the bibliography. There is no instruction to do this in the example document, i.e. this is unsupported.

What happens is that the websites are first displayed due to the command `\nocite{*}` but then, since they appeared in no citation, they are hidden as uncited. This leads to oscillations with the compilation never settling on a stable output.

Anyways, what is the expected outcome here? Should `\nocite{*}` cause the uncited websites to be included in the section `Webseiten` and make the section `Weitere Literatur` be empty? Or can we simple remove `\nocite{*}` from the file `syllabus-de.tex`? The cited websites (KIME, MARICK, and NOVOTNÝ) seem to be copied from the example document and irrelevant to the Syllabus.

**Comment by danopolan** [comment] 2024-11-08 21:13
Oh, I think `\nocite{*}` is not needed. We now have the option to set `further-reading: <bool>` in `metadata.yml` and enable or disable uncited references. I understand this is not the same, but this is enough.
We are using `\nocite{*}` across all products since it's part of .tex files in both product_base and product_template repositories. But I will remove it from everywhere.

**Comment by danopolan** [comment] 2024-11-10 13:11
`\nocite{*}` removed from all repositories and branches, including this repo.

**Comment by danopolan** [comment] 2024-11-10 15:46
@Witiko, all repositories build files after removal of `\nocite{*}` from `.tex` files except this repository due to invalid section reference: `Reference `section:further-reading\' on page 21 undefined on input line 236`
Build: https://github.com/istqborg/istqb_product_base/actions/runs/11765446313/job/32771780075?pr=138

I am not sure why.  Especially when:

- [metadata.yml](https://github.com/istqborg/istqb_product_base/blob/nocite-removed/example-document/metadata.yml#L14) has `further-reading: true`
- further-reading section anchor is defined in [template.py](https://github.com/istqborg/istqb_product_base/blob/nocite-removed/template.py#L62)
- [bibliography.bib](https://github.com/istqborg/istqb_product_base/blob/nocite-removed/example-document/bibliography.bib#L94) contains uncited references

**Comment by Witiko** [comment] 2024-11-11 10:22
Sorry about that! The issue should be fixed after commit https://github.com/istqborg/istqb_product_base/pull/138/commits/8f9cf05859efefee2063e038c186fd4e8dca8225 from https://github.com/istqborg/istqb_product_base/pull/138.

**Closed by Witiko** 2024-11-11 10:22 UTC
